### ISSUE TITLE
Rightmove property index

### ISSUE THREAD

**Issue by rufuspollock** [datasets/house-prices-uk#5]
http://www.rightmove.co.uk/news/house-price-index/previous-editions

Seems to be PDF and no bulk option

**Comment by AcckiyGerman** [comment]
Тhis link does not contain any information ATM (jan2018)

**Comment by rufuspollock** [comment]
@AcckiyGerman ok, a quick search yields http://www.rightmove.co.uk/news/house-price-index/ which suggests it still exists just not at that url.

**Comment by rufuspollock** [comment]
WONTFIX. As this is PDF and not very detailed I suggest we close this as wontfix for now.
